apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: app-template
  namespace: flux-system
spec:
  type: oci
  insecure: true
  url: oci://registry.registry.svc.cluster.local/vendor/charts/app-template
