apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - namespace: test
            app: example
          - namespace: khuedoan
            app: blog
            # - namespace: khuedoan
            #   app: notes
            # - namespace: khuedoan
            #   app: homelab-docs
            # - namespace: finance
            #   app: actualbudget
  template:
    metadata:
      name: '{{.namespace}}-{{.app}}'
    spec:
      project: default # TODO
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      sources:
        - repoURL: 'oci://ghcr.io/bjw-s-labs/helm/app-template'
          targetRevision: 4.2.0
          path: .
          helm:
            valueFiles:
              - $values/apps/{{.namespace}}/{{.app}}/production.yaml
        - repoURL: 'http://forgejo-http.forgejo.svc.cluster.local:3000/khuedoan/cloudlab'
          targetRevision: master
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
