apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: dex
spec:
  destination:
    name: in-cluster
    namespace: dex
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://charts.dexidp.io
    chart: dex
    targetRevision: 0.23.0
    helm:
      valuesObject:
        config:
          issuer: https://dex.cloudlab.khuedoan.com
          storage:
            type: kubernetes
            config:
              inCluster: true
          oauth2:
            passwordConnector: local
            skipApprovalScreen: true
          enablePasswordDB: true
          staticPasswords:
            # uuidgen
            # echo foo | nix-shell -p apacheHttpd --command "htpasswd -BinC 10 admin" | cut -d: -f2
            - username: admin
              email: admin@cloudlab.khuedoan.com
              userID: "b34bd9d2-70ed-4ee1-8d22-6e4fc84f8d17"
              hashFromEnv: ADMIN_PASSWORD_HASH
            - username: khuedoan
              email: mail@khuedoan.com
              userID: "41dd7db5-4cb3-4856-a7f1-0d5168a10a12"
              hashFromEnv: KHUEDOAN_PASSWORD_HASH
          staticClients:
            - id: argocd
              name: ArgoCD
              redirectURIs:
                - 'https://argocd.cloudlab.khuedoan.com/auth/callback'
              secretEnv: ARGOCD_CLIENT_SECRET
            - id: grafana
              name: Grafana
              redirectURIs:
                - 'https://grafana.cloudlab.khuedoan.com/login/generic_oauth'
              secretEnv: GRAFANA_CLIENT_SECRET
            - id: kiali
              name: Kiali
              redirectURIs:
                - 'https://kiali.cloudlab.khuedoan.com'
              secretEnv: KIALI_CLIENT_SECRET
            - id: temporal
              name: Temporal
              redirectURIs:
                - 'https://temporal.cloudlab.khuedoan.com/auth/sso/callback'
              secretEnv: TEMPORAL_CLIENT_SECRET
            - id: forgejo
              name: Forgejo
              redirectURIs:
                - 'https://code.khuedoan.com/user/oauth2/SSO/callback'
              secretEnv: FORGEJO_CLIENT_SECRET
            - id: wireguard
              name: WireGuard
              redirectURIs:
                - 'https://wireguard.cloudlab.khuedoan.com/api/v0/auth/login/sso/callback'
              secretEnv: WIREGUARD_CLIENT_SECRET
        envFrom:
          - secretRef:
              name: dex-secrets
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: dex.cloudlab.khuedoan.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: dex-tls-certificate
              hosts:
                - dex.cloudlab.khuedoan.com
