apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.15.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - grafana.cloudlab.khuedoan.com
          tls:
            - secretName: grafana-general-tls
              hosts:
                - grafana.cloudlab.khuedoan.com
        sidecar:
          dashboards:
            enabled: true
          datasources:
            enabled: true
        envFromSecret: grafana-secrets
        grafana.ini:
          server:
            root_url: https://grafana.cloudlab.khuedoan.com
          auth.generic_oauth:
            enabled: true
            allow_sign_up: true
            name: SSO
            client_id: grafana
            client_secret: $__env{SSO_CLIENT_SECRET}
            scopes: openid profile email groups
            auth_url: https://dex.cloudlab.khuedoan.com/auth
            token_url: https://dex.cloudlab.khuedoan.com/token
          api_url: https://dex.cloudlab.khuedoan.com/userinfo
