apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: netamos
spec:
  destination:
    name: in-cluster
    namespace: netamos
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          restartPolicy: Always
        controllers:
          server:
            labels:
              istio.io/dataplane-mode: ambient
            strategy: RollingUpdate
            containers:
              app:
                image:
                  # TODO switch to netamos
                  repository: registry.registry.svc.cluster.local/khuedoan/platform-engine
                  tag: 3a908a8a0acbf914342dd52f3e768e8e99b44a3e
                  pullPolicy: Always
                command:
                  - /usr/local/bin/server
                env:
                  TEMPORAL_URL: http://temporal-frontend.temporal:7233
                  GITOPS_URL: http://forgejo-http.forgejo.svc.cluster.local:3000/khuedoan/cloudlab
                  GITOPS_REVISION: master
                  REGISTRY: registry.registry.svc.cluster.local:80
          worker:
            labels:
              istio.io/dataplane-mode: ambient
            strategy: RollingUpdate
            pod:
              hostNetwork: true # TODO ???
            containers:
              app:
                image:
                  # TODO switch to netamos
                  repository: registry.registry.svc.cluster.local/khuedoan/platform-engine
                  tag: 3a908a8a0acbf914342dd52f3e768e8e99b44a3e
                  pullPolicy: Always
                env:
                  TEMPORAL_URL: http://temporal-frontend.temporal:7233
                  REGISTRY: registry.registry.svc.cluster.local
                  GIT_USER: Bot
                  GIT_EMAIL: bot@cloudlab.khuedoan.com
                  GIT_USERNAME: khuedoan
                  # TODO generate this automatically
                  GIT_PASSWORD: vault:secret/data/demosecret/forgejo#PASSWORD
              docker:
                image:
                  repository: docker.io/library/docker
                  tag: 27-dind
                command:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --insecure-registry=registry.registry.svc.cluster.local
                securityContext:
                  privileged: true
        service:
          server:
            controller: server
            ports:
              http:
                port: 8080
                protocol: HTTP
        persistence:
          socket:
            type: emptyDir
            advancedMounts:
              worker:
                app:
                  - path: /var/run
                    subPath: docker.sock
                docker:
                  - path: /var/run
                    subPath: docker.sock
