apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: netamos
spec:
  destination:
    name: in-cluster
    namespace: netamos
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          restartPolicy: Always
          hostNetwork: true
        controllers:
          # TODO merge cloudlab controller and app-engine worker
          cloudlab:
            labels:
              istio.io/dataplane-mode: ambient
            strategy: RollingUpdate
            containers:
              worker:
                image:
                  repository: docker.io/khuedoan/cloudlab
                  tag: 03a609
                env:
                  TEMPORAL_HOST: temporal-frontend.temporal:7233
                  TG_NON_INTERACTIVE: true
          app-engine:
            labels:
              istio.io/dataplane-mode: ambient
            strategy: RollingUpdate
            containers:
              worker:
                image:
                  # TODO bootstrap and build itself
                  # repository: zot.zot.svc.cluster.local/khuedoan/app-engine
                  repository: docker.io/khuedoan/app-engine
                  tag: 4118f906ab07a17f3dac608f1a690b2215e4d2a5
                  pullPolicy: Always
                env:
                  TEMPORAL_URL: http://temporal-frontend.temporal:7233
                  REGISTRY: registry.registry.svc.cluster.local
              docker:
                image:
                  repository: docker.io/library/docker
                  tag: 27-dind
                command:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --insecure-registry=registry.registry.svc.cluster.local
                securityContext:
                  privileged: true
        persistence:
          socket:
            type: emptyDir
            advancedMounts:
              app-engine:
                worker:
                  - path: /var/run
                    subPath: docker.sock
                docker:
                  - path: /var/run
                    subPath: docker.sock
