apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: netamos
spec:
  destination:
    name: in-cluster
    namespace: netamos
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          restartPolicy: Always
          hostNetwork: true
        controllers:
          server:
            labels:
              istio.io/dataplane-mode: ambient
            strategy: RollingUpdate
            containers:
              app:
                image:
                  # TODO bootstrap and build itself
                  # repository: zot.zot.svc.cluster.local/khuedoan/platform-engine
                  repository: docker.io/khuedoan/platform-engine
                  tag: de634ba
                  pullPolicy: Always
                command:
                  - /usr/local/bin/server
                env:
                  TEMPORAL_URL: http://temporal-frontend.temporal:7233
          worker:
            labels:
              istio.io/dataplane-mode: ambient
            strategy: RollingUpdate
            containers:
              app:
                image:
                  # TODO bootstrap and build itself
                  # repository: zot.zot.svc.cluster.local/khuedoan/platform-engine
                  repository: docker.io/khuedoan/platform-engine
                  tag: de634ba
                  pullPolicy: Always
                env:
                  TEMPORAL_URL: http://temporal-frontend.temporal:7233
                  REGISTRY: registry.registry.svc.cluster.local
              docker:
                image:
                  repository: docker.io/library/docker
                  tag: 27-dind
                command:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --insecure-registry=registry.registry.svc.cluster.local
                securityContext:
                  privileged: true
        service:
          server:
            controller: server
            ports:
              http:
                port: 8080
                protocol: HTTP
        persistence:
          socket:
            type: emptyDir
            advancedMounts:
              worker:
                app:
                  - path: /var/run
                    subPath: docker.sock
                docker:
                  - path: /var/run
                    subPath: docker.sock
