apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: wireguard
spec:
  destination:
    name: in-cluster
    namespace: wireguard
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: oci://ghcr.io/h44z/charts/wg-portal
    targetRevision: 0.7.1
    helm:
      valuesObject:
        config:
          core:
            create_default_peer: true
            self_provisioning_allowed: true
          web:
            external_url: https://wireguard.cloudlab.khuedoan.com
          auth:
            hide_login_form: true
            oidc:
              - id: sso
                provider_name: sso
                display_name: Login with SSO
                registration_enabled: true
                base_url: https://dex.cloudlab.khuedoan.com
                client_id: wireguard
                client_secret: $SSO_CLIENT_SECRET
                extra_scopes:
                  - profile
                  - email
                field_map:
                  is_admin: email
                admin_mapping:
                  admin_value_regex: ^admin@cloudlab.khuedoan.com$
        envFrom:
          - secretRef:
              name: wireguard-secret
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls: true
        persistence:
          enabled: true
