services:
  temporal:
    image: docker.io/temporalio/server:1.27
    entrypoint:
      - temporal
      - server
      - start-dev
      - --ip=0.0.0.0
    ports:
      - 7233:7233
      - 8233:8233
    healthcheck:
      test: tctl workflow list
      start_period: 5s
  worker:
    build: ./controller
    environment:
      TEMPORAL_HOST: temporal:7233
    depends_on:
      temporal:
        condition: service_healthy
