secrets:
  secret/khuedoan/notes/password:
    VALUE:
      type: random
      length: 32 # optional, default 32
  secret/git/deploy:
    admin:
      type: ssh
  secret/platform/cloudflare:
    API_TOKEN:
      type: manual
      description: |
        Enter Cloudflare API token:
        (Generate it from https://dash.cloudflare.com -> Manage account -> Account API tokens)
  secret/forgejo/admin:
    password:
      type: random
  # TODO maybe centralize to Dex
  secret/forgejo/oauth:
    key:
      type: random
    secret:
      type: random
  secret/actualbudget/auth:
    client_secret:
      type: random
  secret/temporal/oauth:
    client_secret:
      type: random
  secret/temporal/postgresql:
    password:
      type: random
  secret/dex/auth:
    ADMIN_PASSWORD_HASH:
      type: manual
      description: |
        Enter Dex admin password hash.
        (Generate with: echo mypassword | htpasswd -BinC 10 "" | cut -d: -f2)
    KHUEDOAN_PASSWORD_HASH:
      type: manual
      description: |
        Enter Dex khuedoan password hash.
        (Generate with: echo mypassword | htpasswd -BinC 10 "" | cut -d: -f2)
vendors:
  vendor/charts/cloudnative-pg:
    kind: chart
    repo_url: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    versions:
      - 0.28.0
  vendor/images/cloudnative-pg/cloudnative-pg:
    kind: image
    source: ghcr.io/cloudnative-pg/cloudnative-pg
    versions:
      - 1.29.0
  vendor/images/cloudnative-pg/postgresql:
    kind: image
    source: ghcr.io/cloudnative-pg/postgresql
    versions:
      - 17.6-system-trixie
  vendor/charts/dex:
    kind: chart
    repo_url: https://charts.dexidp.io
    chart: dex
    versions:
      - 0.23.0
  vendor/charts/temporal:
    kind: chart
    repo_url: https://go.temporal.io/helm-charts
    chart: temporal
    versions:
      - 0.58.0
  vendor/images/dexidp/dex:
    kind: image
    source: ghcr.io/dexidp/dex
    versions:
      - v2.43.1
