apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# TODO clean this up, leaving it here for easy rollback
- deployment.yaml
# - deployment-rust.yaml
- service.yaml
- ingress.yaml
