app-template:
  controllers:
    main:
      replicas: 2
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: docker.io/khuedoan/blog
            tag: 1259d8d5f0c8b411003f68ff413190a9401f405f
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: www.khuedoan.com
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: 3000
      tls:
      - hosts:
        - www.khuedoan.com
        secretName: blog-tls-certificate
