app-template:
  controllers:
    main:
      replicas: 2
      strategy: RollingUpdate
      containers:
        main:
          image:
            repository: docker.io/khuedoan/blog
            tag: 2f43b1d18371a9ccbc9cc0e2d541f9fd952fc6d3
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host www.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: 3000
      tls:
        - hosts:
            - *host
          secretName: blog-tls-certificate
