app-template:
  controllers:
    main:
      replicas: 2
      containers:
        main:
          image:
            repository: docker.io/khuedoan/blog
            tag: 939aa5d90e7e5f60dfa81e80508786c149a7612a
  service:
    main:
      controller: main
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host www.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: 3000
      tls:
        - hosts:
            - *host
          secretName: blog-tls-certificate
