apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: example-service
spec:
  destination:
    name: in-cluster
    namespace: example-service
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          labels:
            istio.io/dataplane-mode: ambient
        controllers:
          main:
            replicas: 2
            strategy: RollingUpdate
            containers:
              main:
                image:
                  repository: zot.zot.svc.cluster.local/example-service
                  tag: 828c31f942e8913ab2af53a2841c180586c5b7e1
        service:
          main:
            controller: main
            ports:
              http:
                port: 8080
                protocol: HTTP
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: example.127-0-0-1.nip.io
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: 8080
            tls:
              - hosts:
                  - example.127-0-0-1.nip.io
                secretName: example-tls-certificate
