apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-app
  instances: 1
  storage:
    size: 1Gi
