apiVersion: apps.netamos.com/v1alpha1
kind: Application
metadata:
  name: actualbudget
spec:
  source:
    kind: image
  image: docker.io/actualbudget/actual-server:latest-alpine
  port: 5006
  domains:
    - budget.khuedoan.com
    - budget.production.khuedoan.com
  env:
    - key: ACTUAL_LOGIN_METHOD
      value: openid
      source: Plain
    - key: ACTUAL_OPENID_DISCOVERY_URL
      value: https://dex.production.khuedoan.com/.well-known/openid-configuration
      source: Plain
    - key: ACTUAL_OPENID_CLIENT_ID
      value: actualbudget
      source: Plain
    - key: ACTUAL_OPENID_SERVER_HOSTNAME
      value: https://budget.khuedoan.com
      source: Plain
    - key: ACTUAL_USER_CREATION_MODE
      value: login
      source: Plain
    - key: ACTUAL_OPENID_CLIENT_SECRET
      value: vault:secret/data/actualbudget/auth#client_secret
      source: Secret
  volume:
    mountPath: /data
    size: 1Gi
