apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: actualbudget
    app.kubernetes.io/managed-by: netamos
    app.kubernetes.io/name: actualbudget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
