apiVersion: v1
kind: Secret
metadata:
  name: actualbudget
  annotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.vault.svc.cluster.local:8200
    vault.security.banzaicloud.io/vault-path: kubernetes
    vault.security.banzaicloud.io/vault-role: default
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: actualbudget
    app.kubernetes.io/managed-by: netamos
    app.kubernetes.io/name: actualbudget
stringData:
  ACTUAL_OPENID_CLIENT_SECRET: vault:secret/data/actualbudget/auth#client_secret
