apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget
  namespace: finance-actualbudget-production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
