apiVersion: v1
kind: Service
metadata:
  name: actualbudget
  namespace: finance-actualbudget-production
spec:
  ports:
  - name: http
    port: 5006
    targetPort: http
  selector:
    app.kubernetes.io/name: actualbudget
