apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: gerrit
spec:
  destination:
    name: in-cluster
    namespace: gerrit
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          labels:
            "istio.io/dataplane-mode": "ambient"
        controllers:
          main:
            containers:
              main:
                image:
                  repository: docker.io/gerritcodereview/gerrit
                  tag: 3.12.0
                env:
                  CANONICAL_WEB_URL: http://127.0.0.1.sslip.io
        service:
          main:
            controller: main
            ports:
              ssh:
                port: 29418
                protocol: TCP
              http:
                port: 8080
                protocol: TCP
        ingress:
          main:
            enabled: true
            className: nginx
            hosts:
              - host: code.127.0.0.1.sslip.io
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: 8080
        persistence:
          data:
            accessMode: ReadWriteOnce
            size: 10Gi
            advancedMounts:
              main:
                main:
                  - path: /var/gerrit/git
                    subPath: git
                  - path: /var/gerrit/db
                    subPath: db
                  - path: /var/gerrit/index
                    subPath: index
