apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kiali
spec:
  destination:
    name: in-cluster
    namespace: istio-system
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 2.7.1
    helm:
      valuesObject:
        auth:
          strategy: openid
          openid:
            client_id: kiali
            issuer_uri: https://dex.127.0.0.1.sslip.io
            disable_rbac: true
        external_services:
          prometheus:
            url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
          grafana:
            enabled: false
        deployment:
          view_only_mode: true
          ingress:
            enabled: true
            override_yaml:
              metadata:
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
              spec:
                ingressClassName: nginx
                rules:
                  - host: kiali.127.0.0.1.sslip.io
                    http:
                      paths:
                        - backend:
                            service:
                              name: kiali
                              port:
                                name: http
                          path: /
                          pathType: Prefix
                tls:
                  - hosts:
                      - kiali.127.0.0.1.sslip.io
                    secretName: kiali-tls-certificate
        server:
          web_fqdn: kiali.127.0.0.1.sslip.io
          web_root: /
