apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: wireguard
spec:
  destination:
    name: in-cluster
    namespace: wireguard
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        controllers:
          wireguard:
            containers:
              app:
                image:
                  repository: lscr.io/linuxserver/wireguard
                  tag: latest
                env:
                  LOG_CONFS: false
                  USE_COREDNS: true
                securityContext:
                  capabilities:
                    add:
                      - NET_ADMIN
        service:
          wireguard:
            controller: wireguard
            type: LoadBalancer
            ports:
              http:
                port: 51820
                protocol: UDP
        persistence:
          config:
            type: secret
            name: "wireguard-secret"
            globalMounts:
              - path: /config/wg_confs
