apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 3m
  dependsOn:
    - name: platform-namespaces
  chart:
    spec:
      chart: base
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-base
  targetNamespace: istio-system
  install:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  interval: 3m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: cni
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istio-cni
  targetNamespace: istio-system
  values:
    global:
      platform: k3s
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: flux-system
spec:
  interval: 3m
  dependsOn:
    - name: istio-cni
  chart:
    spec:
      chart: ztunnel
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: ztunnel
  targetNamespace: istio-system
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 3m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
  releaseName: istiod
  targetNamespace: istio-system
  values:
    profile: ambient
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: cert-manager-config
    - name: istiod
  releaseName: istio-gateway
  targetNamespace: istio-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: app-template
  values:
    rawResources:
      gateway:
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        forceRename: gateway
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        spec:
          spec:
            gatewayClassName: istio
            listeners:
              - name: https
                # TODO configurable
                hostname: "*.staging.khuedoan.com"
                port: 443
                protocol: HTTPS
                tls:
                  certificateRefs:
                    - name: wildcard-tls
                allowedRoutes:
                  namespaces:
                    from: All
