apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: platform-namespaces
  namespace: flux-system
spec:
  interval: 30m
  releaseName: platform-namespaces
  targetNamespace: flux-system
  install:
    remediation:
      retries: -1
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: app-template
  values:
    rawResources:
      cert-manager:
        apiVersion: v1
        kind: Namespace
        forceRename: cert-manager
        spec: {}
      cnpg-system:
        apiVersion: v1
        kind: Namespace
        forceRename: cnpg-system
        spec: {}
      dex:
        apiVersion: v1
        kind: Namespace
        forceRename: dex
        spec: {}
      istio-system:
        apiVersion: v1
        kind: Namespace
        forceRename: istio-system
        spec: {}
      temporal:
        apiVersion: v1
        kind: Namespace
        forceRename: temporal
        spec: {}
