apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netamos
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: platform-namespaces
    - name: temporal
    - name: forgejo
  releaseName: netamos
  targetNamespace: netamos
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: app-template
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: app-template
  values:
    route:
      netamos:
        parentRefs:
          - name: gateway
            namespace: istio-system
        hostnames:
          - netamos.staging.khuedoan.com
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: netamos
                port: 8080
    controllers:
      server:
        pod:
          annotations:
            vault.security.banzaicloud.io/vault-addr: http://vault.vault.svc.cluster.local:8200
            vault.security.banzaicloud.io/vault-role: default
            vault.security.banzaicloud.io/vault-path: kubernetes
        containers:
          app:
            image:
              repository: docker.io/khuedoan/netamos
              tag: da80426de520eac53522591167403f9dabcdd854
            command:
              - /usr/local/bin/server
            env:
              NETAMOS_TEMPORAL_URL: http://temporal-frontend.temporal:7233
              NETAMOS_TEMPORAL_NAMESPACE: default
              NETAMOS_FORGEJO_URL: http://forgejo-http.forgejo.svc.cluster.local:3000
              NETAMOS_FORGEJO_ADMIN_USERNAME: forgejo_admin
              NETAMOS_FORGEJO_ADMIN_PASSWORD: vault:secret/data/forgejo/admin#password
              NETAMOS_FORGEJO_USERNAME: Bot
              NETAMOS_FORGEJO_PASSWORD: vault:secret/data/netamos/forgejo#password
              NETAMOS_REGISTRY: registry.registry.svc.cluster.local
              NETAMOS_GITOPS_OWNER: khuedoan
              NETAMOS_GITOPS_REPO: cloudlab
              NETAMOS_GITOPS_BRANCH: master
              NETAMOS_GITOPS_AUTHOR_NAME: Bot
              NETAMOS_GITOPS_AUTHOR_EMAIL: bot@cloudlab.khuedoan.com
              NETAMOS_WEBHOOK_SECRET: vault:secret/data/netamos/webhook#secret
              NETAMOS_BOOTSTRAP_WEBHOOK_URL: http://netamos.netamos.svc.cluster.local:8080/webhooks/forgejo
              NETAMOS_AUTH_ISSUER_URL: https://dex.staging.khuedoan.com
              NETAMOS_AUTH_CLIENT_ID: netamos
              NETAMOS_AUTH_CLIENT_SECRET: vault:secret/data/netamos/oauth#client_secret
              NETAMOS_AUTH_REDIRECT_URL: https://netamos.staging.khuedoan.com/auth/callback
              NETAMOS_AUTH_COOKIE_KEY: vault:secret/data/netamos/cookie#key
              NETAMOS_AUTH_COOKIE_SECURE: "true"
      worker:
        pod:
          hostNetwork: true # TODO ???
          annotations:
            vault.security.banzaicloud.io/vault-addr: http://vault.vault.svc.cluster.local:8200
            vault.security.banzaicloud.io/vault-role: default
            vault.security.banzaicloud.io/vault-path: kubernetes
          hostAliases:
            - ip: 2a01:4f8:c010:d56::2
              hostnames:
                - github.com
            - ip: 2a01:4f8:c010:d56::4
              hostnames:
                - codeload.github.com
            - ip: 2a01:4f8:c010:d56::6
              hostnames:
                - ghcr.io
        containers:
          app:
            image:
              repository: docker.io/khuedoan/netamos
              tag: da80426de520eac53522591167403f9dabcdd854
            command:
              - /usr/local/bin/worker
            env:
              NETAMOS_TEMPORAL_URL: http://temporal-frontend.temporal:7233
              NETAMOS_TEMPORAL_NAMESPACE: default
              NETAMOS_FORGEJO_URL: http://forgejo-http.forgejo.svc.cluster.local:3000
              NETAMOS_FORGEJO_USERNAME: Bot
              NETAMOS_FORGEJO_PASSWORD: vault:secret/data/netamos/forgejo#password
              NETAMOS_FORGEJO_ADMIN_USERNAME: forgejo_admin
              NETAMOS_FORGEJO_ADMIN_PASSWORD: vault:secret/data/forgejo/admin#password
              NETAMOS_REGISTRY: registry.registry.svc.cluster.local
              NETAMOS_GITOPS_OWNER: khuedoan
              NETAMOS_GITOPS_REPO: cloudlab
              NETAMOS_GITOPS_BRANCH: master
              NETAMOS_GITOPS_AUTHOR_NAME: Bot
              NETAMOS_GITOPS_AUTHOR_EMAIL: bot@cloudlab.khuedoan.com
              NETAMOS_WEBHOOK_SECRET: vault:secret/data/netamos/webhook#secret
              NETAMOS_BOOTSTRAP_WEBHOOK_URL: http://netamos.netamos.svc.cluster.local:8080/webhooks/forgejo
              DOCKER_BUILD_NETWORK: host
              DOCKER_BUILD_ADD_HOSTS: github.com:2a01:4f8:c010:d56::2,codeload.github.com:2a01:4f8:c010:d56::4
          docker:
            image:
              repository: docker.io/library/docker
              tag: 27-dind
            command:
              - dockerd
              - --host=unix:///var/run/docker.sock
              - --insecure-registry=registry.registry.svc.cluster.local
            securityContext:
              privileged: true
    service:
      server:
        controller: server
        ports:
          http:
            port: 8080
            protocol: HTTP
    persistence:
      socket:
        type: emptyDir
        advancedMounts:
          worker:
            app:
              - path: /var/run
                subPath: docker.sock
            docker:
              - path: /var/run
                subPath: docker.sock
