apiVersion: apps/v1
kind: Deployment
metadata:
  name: hn4e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hn4e
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hn4e
    spec:
      containers:
      - image: registry.registry.svc.cluster.local/apps/khuedoan/hn4e:ba120ddc5f6197b08087e0159b5ddbf66d1bce61
        name: hn4e
        ports:
        - containerPort: 3001
          name: http
