apiVersion: apps/v1
kind: Deployment
metadata:
  name: hn4e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hn4e
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hn4e
    spec:
      containers:
      - image: registry.registry.svc.cluster.local/apps/khuedoan/hn4e:b48fdc07b56d91a073d89b7b76cd88053e6bfc11
        name: hn4e
        ports:
        - containerPort: 3001
          name: http
