defaultPodOptions:
  labels:
    istio.io/dataplane-mode: ambient
controllers:
  main:
    type: statefulset
    containers:
      main:
        image:
          repository: ghcr.io/silverbulletmd/silverbullet
          tag: v2
        envFrom:
          - secret: silverbullet
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
        protocol: HTTP
route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: istio-system
    hostnames:
      - notes.staging.khuedoan.com
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: 3000
persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /space
