creation_rules:
  # TODO auto manage age keys, currently have to:
  # - run age-keygen
  # - copy public key here
  # - copy private key to ~/.config/sops/age/keys.txt
  # TODO fix this shit and don't share secrets between staging and prod
  - age: >-
      age15c5rpksj0u27sp667525zqh8dhtd70rwrlv7xq2hqhsfaempcdwqu3unel,
      age1j9vhx20vkmepd4e7tze5dc6f2lm4gt4wa7zskhcq2k9xw93c8e3qvpd4dx
