- name: Iptables flush filter
  ansible.builtin.iptables:
    flush: yes
- name: Disable netfilter service
  systemd:
    name: netfilter-persistent
    enabled: false
    state: stopped
- name: Adjust kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - {name: "fs.inotify.max_queued_events", value: 16384}
    - {name: "fs.inotify.max_user_instances", value: 8192}
    - {name: "fs.inotify.max_user_watches", value: 524288}
