app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/moby/buildkit
            tag: rootless
          args:
            - --addr=tcp://0.0.0.0:1234
            - --oci-worker-no-process-sandbox
          securityContext:
            appArmorProfile:
              type: Unconfined
  service:
    main:
      controller: main
      ports:
        http:
          port: 1234
          protocol: TCP
