app-template:
  controllers:
    ollama:
      containers:
        app:
          image:
            repository: docker.io/ollama/ollama
            tag: 0.3.5
  service:
    ollama:
      controller: ollama
      ports:
        http:
          port: 11434
          protocol: HTTP
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        ollama:
          app:
            - path: /root/.ollama
