app-template:
  controllers:
    server:
      initContainers:
        auth:
          image:
            repository: docker.io/khuedoan/radicle-server
            tag: latest
          env:
            RAD_HOME: /var/lib/radicle
            RAD_PASSPHRASE: ""
          command:
            - rad
            - auth
            - --alias=radicle.horus.khuedoan.com
      containers:
        node:
          image:
            repository: docker.io/khuedoan/radicle-server
            tag: latest
          env:
            RAD_HOME: /var/lib/radicle
          command:
            - radicle-node
        api:
          image:
            repository: docker.io/khuedoan/radicle-server
            tag: latest
          env:
            RAD_HOME: /var/lib/radicle
          command:
            - radicle-httpd
    explorer:
      containers:
        main:
          image:
            repository: docker.io/khuedoan/radicle-explorer
            tag: latest
  service:
    server:
      controller: server
      ports:
        radicle:
          port: 8776
          protocol: TCP
        http:
          port: 8080
          protocol: HTTP
    explorer:
      controller: explorer
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: radicle.horus.khuedoan.com
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: server
            port: 8080
      - host: code.horus.khuedoan.com
        paths:
        - path: /
          pathType: Prefix
          service:
            identifier: explorer
            port: 80
      tls:
      - hosts:
        - radicle.horus.khuedoan.com
        - code.horus.khuedoan.com
        secretName: radicle-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        server:
          auth:
            - path: /var/lib/radicle
          node:
            - path: /var/lib/radicle
          api:
            - path: /var/lib/radicle
