- name: Create secrets
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
        annotations:
          app.kubernetes.io/managed-by: Ansible
      type: Opaque
      stringData: "{{ item.stringData }}"
  loop:
    # TODO fix potential chicken and eggs issue
    - name: gha-runner-khuedoan
      namespace: github-actions
      stringData:
        github_token: "{{ github_actions_token_khuedoan }}"
