defaultPodOptions:
  labels:
    "istio.io/dataplane-mode": "ambient"
controllers:
  main:
    replicas: 2
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: docker.io/khuedoan/blog
          tag: 6fbd90b77a81e0bcb330fddaa230feff744a7010
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
        protocol: HTTP
ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: www.127.0.0.1.sslip.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: 3000
    tls:
      - hosts:
          - www.127.0.0.1.sslip.io
        secretName: blog-tls-certificate
