defaultPodOptions:
  labels:
    istio.io/dataplane-mode: ambient
controllers:
  main:
    replicas: 2
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: registry.registry.svc.cluster.local/khuedoan/blog
          tag: 6cb03fda54611c949a9a85fe59a94f9c8e061e51
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
        protocol: HTTP
ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - host: www.khuedoan.com
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: 3000
    tls:
    - hosts:
      - www.khuedoan.com
      secretName: blog-tls-certificate
