defaultPodOptions:
  labels:
    istio.io/dataplane-mode: ambient
controllers:
  main:
    replicas: 2
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: registry.registry.svc.cluster.local/khuedoan/blog
          tag: b1e6bb730ce8193e10a6981d59e509132cfaa749
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
        protocol: HTTP
route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: istio-system
    hostnames:
      - www.production.khuedoan.com
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: 3000
