apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: actualbudget
spec:
  destination:
    name: in-cluster
    namespace: actualbudget
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          labels:
            "istio.io/dataplane-mode": "ambient"
        controllers:
          main:
            containers:
              main:
                image:
                  repository: docker.io/actualbudget/actual-server
                  tag: 25.6.1-alpine
        service:
          main:
            controller: main
            ports:
              http:
                port: 5006
                protocol: HTTP
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: budget.cloudlab.khuedoan.com
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http
            tls:
              - hosts:
                  - budget.cloudlab.khuedoan.com
                secretName: actualbudget-tls-certificate
        persistence:
          data:
            accessMode: ReadWriteOnce
            size: 1Gi
            globalMounts:
              - path: /data
