apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: blog
spec:
  destination:
    name: in-cluster
    namespace: blog
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          labels:
            istio.io/dataplane-mode: ambient
        controllers:
          main:
            replicas: 2
            strategy: RollingUpdate
            containers:
              main:
                image:
                  repository: docker.io/khuedoan/blog
                  tag: 1.2.3
        service:
          main:
            controller: main
            ports:
              http:
                port: 3000
                protocol: HTTP
        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
            - host: www.khuedoan.com
              paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: 3000
            tls:
            - hosts:
              - www.khuedoan.com
              secretName: blog-tls-certificate
