app-template:
  defaultPodOptions:
    labels:
      "istio.io/dataplane-mode": "ambient"
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/actualbudget/actual-server
            tag: 25.6.1-alpine
  service:
    main:
      ports:
        http:
          port: 5006
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host budget.cloudlab.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: actualbudget-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /data
