defaultPodOptions:
  labels:
    istio.io/dataplane-mode: ambient
controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/actualbudget/actual-server
          tag: latest-alpine
service:
  main:
    controller: main
    ports:
      http:
        port: 5006
        protocol: HTTP
route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: istio-system
    hostnames:
      - budget.staging.khuedoan.com
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: 5006
persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /data
