defaultPodOptions:
  labels:
    istio.io/dataplane-mode: ambient
controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/actualbudget/actual-server
          tag: latest-alpine
        env:
          ACTUAL_LOGIN_METHOD: openid
          ACTUAL_OPENID_DISCOVERY_URL: https://dex.staging.khuedoan.com/.well-known/openid-configuration
          ACTUAL_OPENID_CLIENT_ID: actualbudget
          ACTUAL_OPENID_CLIENT_SECRET: vault:secret/data/actualbudget/auth#client_secret
          ACTUAL_OPENID_SERVER_HOSTNAME: https://budget.staging.khuedoan.com
          ACTUAL_USER_CREATION_MODE: login
service:
  main:
    controller: main
    ports:
      http:
        port: 5006
        protocol: HTTP
route:
  main:
    kind: HTTPRoute
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: gateway
        namespace: istio-system
    hostnames:
      - budget.staging.khuedoan.com
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: 5006
persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /data
