cloudflare_tfstate_api_token: ENC[AES256_GCM,data:XYtgdd+Xi0evZTyWOzoL6zj74FJJiijdPO3KGwrBus6OhmGCbJSSXw==,iv:Hx4BFeec4n+88Agto5RzSK7E3dift84W9Gbjj0KWS6g=,tag:xP3mnJnliR1M8Eeer4sAow==,type:str]
cloudflare_tfstate_access_key: ENC[AES256_GCM,data:35GI8IiVUCTseqh9gLqjMnFYutXS5wxVcgKke16CZgA=,iv:6ixZ5fbaW9PtgFtSGsQwdNwNFpkqnX4FNIrJhWUVnos=,tag:qS5WuN05G4vvxnFuhjshOA==,type:str]
cloudflare_tfstate_secret_key: ENC[AES256_GCM,data:+EL39un0LoIG+9Oxf80iRdBun2kAWzpCuif7aCX4WQZLQ16eWK8QYv4Cylyu4QBnUdksLgRGkh7MJ93TNsWBUQ==,iv:3AMj8mylIkR/LM+5B0HDygsv5vSlfRGbXhE9jjk6bZI=,tag:TJWwWiTwRXw/sYfTMmBvRA==,type:str]
cloudflare_account_id: ENC[AES256_GCM,data:1Ucwh92YRCU97O/TBQZh02HIDp/s902Dg6GL7s3xmR0=,iv:/O7ez1bwCSktYgG/vj5RvXB+A3tmlGO5PYZ+BBM9Kv8=,tag:SH/T5Ez0TtmCwPOWpzj65A==,type:str]
sops:
    age:
        - recipient: age1j9vhx20vkmepd4e7tze5dc6f2lm4gt4wa7zskhcq2k9xw93c8e3qvpd4dx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVjZFb1BpdFl3S0VXZlRY
            R1hFbEZJMlNZU0R2Tkl5amc0Z2F6NVlCaGpzCnZsZ3BFL3BkQmw4Wm1ybitFTmJm
            OVlORlduVmU5dVArc2FHaXB4a1hhejQKLS0tIFJxYXE5NEVDQnF6NnVTS1JkamFR
            WE41Mk9SRDlnNG5KTTFYT0pqclZISzAKKvYxrXkxVRB7KJFvADUIgh3lVwJTFaiz
            Y4ww84MOhWmlivqJ4XFOqxa3XA7qQLemSUdOIptdg5XQwZiVnW1F0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T15:57:49Z"
    mac: ENC[AES256_GCM,data:AdIcoSCsx0kAUhAIEH1XNaizjWw36DP3sV01oszo2h5qDpnbqfYzRzlTpSyp7uooSZeWSqE4aBaA/J/iIvDW0W/Ph+NvnePJYCNwjz4p7LeLSKStMXB/YgZ4bfL4BL2W3KhFJAALbF1ImM/MCP0z3OFWn66qouk99MufFHYVs3E=,iv:vhwyBIOzwBJQCVgYQStwz/XCQaDZHJmnpvBfraLzMWk=,tag:U1sKYyX8Mm2yhdfhIttp8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
