apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-runs
resources:
  - ./namespace.yaml
  # Default tasks
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildpacks/0.6/buildpacks.yaml
  - https://raw.githubusercontent.com/tektoncd/catalog/main/task/git-clone/0.9/git-clone.yaml
  # Default pipelines
  - ./eventlistener.yaml
